package com.example.geochallenge.ui.auth

enum class AuthErrors {
    NONE,
    USERNAME_ALREADY_IN_USE,
    EMAIL_ALREADY_IN_USE,
    NOT_CORRECT_EMAIL,
    SHORT_PASSWORD,
    REGISTRATION_FAILED,
    FIELD_USERNAME_IS_EMPTY,
    FIELD_PASSWORD_IS_EMPTY,
    FIELD_EMAIL_IS_EMPTY,
    WRONG_PASSWORD,
    INVALID_USER,
    TO_MANY_REQUESTS
//    WRONG_EMAIL
}